http:
  routers:
    httpbin-http:
      rule: " Host(`0.0.0.0`)"
      entryPoints:
        - http
      service: httpbin
    httpbin-https:
      rule: "Host(`0.0.0.0`)"
      entryPoints:
        - https
      service: httpbin
      tls: true

  services:
    httpbin:
      loadBalancer:
        servers:
          - url: "http://httpbin1:80"
          - url: "http://httpbin2:80"
          - url: "http://httpbin3:80"
          - url: "http://httpbin4:80"
          - url: "http://httpbin5:80"
        passHostHeader: true
